### ISSUE TITLE
Simargs support subcommands

### ISSUE THREAD

**Issue by jiacai2050** [jiacai2050/zigcli#22]
For now, simargs doesn't sub commands, add subcommands support will make it much more powerful.

The syntax I could think of is like this:

``` zig
const App = struct {
    help: bool = false,
    output: []const u8,

    sub_command1: ?struct {
        flags1: int,
    },

    sub_command2: ?struct {
        flags1: int,
    },
};

```

Since there are more than one subcommand, we use optional to annotate them.

Or we can represent subcommand with `union(enum)`

``` zig
const App = struct {
    help: bool = false,
    output: []const u8,

    sub_command: union(enum) {
        sub_cmd1: struct {
            flag1: i8,
        },
        sub_cmd2: struct {
            flag1: i8,
        },
    },
};
```

Here both method use nested struct to represent subcommands, and it can be nested at any-level!

The help message would look like this:

``` shell
Usage: mycli [Global-Options] [COMMAND] [Options]

Commands:
  sub_command1  xxx
  sub_command2  yyy

Options:
  -o, --output <file>           Output file
  -h, --help                    Print help
```

**Comment by clickingbuttons** [comment]
I prefer the union enum approach.

**Comment by jiacai2050** [comment]
Thanks, I also like the union style. I will implement this feature in next few weeks.
